### ISSUE TITLE
Duplicate fetch key detected

### ISSUE THREAD

**Issue by Quineone** [GrabarzUndPartner/nuxt-speedkit#648]
**Describe the bug**
Duplicate fetch key detected

**To Reproduce**
1. Create `a.vue` component and use the SpeedkitImage inside
2. Use the `a.vue` component for multi components

**Expected behavior**
```js
fetchKey(getCounter) {
    // getCounter is a method that can be called to get the next number in a sequence
    // as part of generating a unique fetchKey.
    if (this.source) {
      return (
        `image-${new Source(this.source)?.key}${getCounter('speedkit-image')}`
      )
    }
    return 'image'
  },

**Comment by ThornWalli** [comment]
Hello @Quineone,

should have finished the issue first...

This (#650) is only a small adjustment in the PR in relation to the `SpeedkitImage`.

The warning can come if:

1. a source is used more than once on a page. The source key is the source path as hex string therefore identical fetch keys and is correct because each fetch should be done only once.
2. if no source is assigned, then the fetch key image is set by default.
3. when using the `SpeedkitPicture` causes this message because there for the `<img />` a `SpeedkitImage` is used. In this case the `SpeedkitImage` has an empty fetch, because the sources are used over the fetch of the Picture.

We do not use a random at this point because otherwise unnecessary fetch keys are in the payload.

Do they install identical images on one page in multiple components?

**Comment by Quineone** [comment]
Yes, it should be possible. Image you have a componnet that need to show different layout for mobile and desktop, but they are use the same image source.

**Comment by ThornWalli** [comment]
@Quineone Is solved now, with `getCounter`.
